# Generated by Django 6.0.3 on 2026-03-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usertourprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTourProgress',
        ),
    ]
