# Generated by Django 6.0.3 on 2026-03-27 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_usertourprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpoint',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Уникальный код для сканирования QR', max_length=100, verbose_name='QR код точки'),
        ),
        migrations.CreateModel(
            name='UserTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершен'), ('abandoned', 'Покинут')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_point_order', models.IntegerField(default=0, verbose_name='Текущая точка')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tours', to='main.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тур пользователя',
                'verbose_name_plural': 'Туры пользователей',
                'unique_together': {('user', 'tour', 'status')},
            },
        ),
        migrations.CreateModel(
            name='UserTourPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tourpoint')),
                ('user_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_points', to='main.usertour')),
            ],
            options={
                'verbose_name': 'Пройденная точка',
                'verbose_name_plural': 'Пройденные точки',
                'unique_together': {('user_tour', 'point')},
            },
        ),
    ]
