# Generated by Django 6.0.3 on 2026-03-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usertour_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpoint',
            name='facts',
            field=models.TextField(blank=True, help_text='Интересные факты о точке, которые отобразятся после прохождения', verbose_name='Интересные факты'),
        ),
    ]
