# Generated by Django 6.0.3 on 2026-03-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tourpoint_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Изображение тура'),
        ),
    ]
