# Generated by Django 6.0.3 on 2026-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shopitem_userprofile_userpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=1, verbose_name='Сложность 1-5'),
        ),
    ]
