# Generated by Django 6.0.3 on 2026-03-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tour_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=1, verbose_name='Рейтинг 1-5'),
        ),
    ]
