# Generated by Django 6.0.3 on 2026-03-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tour_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpoint',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание где искать следующую точку'),
        ),
    ]
