# Generated by Django 6.0.3 on 2026-03-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tourpoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertour',
            name='rewards_given',
            field=models.BooleanField(default=False, help_text='Были ли уже выданы монеты за этот тур', verbose_name='Награды выданы'),
        ),
    ]
