# Generated by Django 6.0.3 on 2026-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_usertour_rewards_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = бесплатно (зеленый), 1-1000 = желтый, >1000 = красный', max_digits=10, verbose_name='Цена (₽)'),
        ),
    ]
